micronaut:
  application:
    name: protoBuf

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    fretes:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

endpoints:
  health:
    enabled: true
    sensitive: true
    details-visible: AUTHENTICATED
